#!/bin/bash
# ==============================================================================
# Community Hass.io Add-ons: Plejd
# Runs the Plejd service
# ==============================================================================

echo 'Starting the Plejd service...'

# Change working directory
cd /plejd || (>&2 echo 'Unable to change working directory'; exit $ERRCODE)

# Run the Plejd service
echo 'Verifying permissions on startup script'
chmod +x /usr/bin/plejd.sh

echo 'Executing startup script'
exec /usr/bin/plejd.sh
